FROM python:2.7

MAINTAINER Pan Luo <pan.luo@ubc.ca>

ENV PYTHONUNBUFFERED 1
#ENV NGINX_VERSION 1.9.11-1~jessie

# apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 \
#	&& echo "deb http://nginx.org/packages/mainline/debian/ jessie nginx" >> /etc/apt/sources.list \
RUN	apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y \
#	    ca-certificates \
#	    nginx=${NGINX_VERSION} gettext-base \
        npm nodejs-legacy \
    && easy_install distribute \
    && pip install uwsgi \
    && mkdir /code \
	&& rm -rf /var/lib/apt/lists/*

# forward request and error logs to docker log collector
#RUN ln -sf /dev/stdout /var/log/nginx/access.log \
#	&& ln -sf /dev/stderr /var/log/nginx/error.log \
#    # Make NGINX run on the foreground
#    && echo "daemon off;" >> /etc/nginx/nginx.conf \
#    # Remove default configuration from Nginx
#    && rm /etc/nginx/conf.d/default.conf

# Copy the modified Nginx conf
#COPY deploy/docker/nginx.conf /etc/nginx/conf.d/
# Copy the base uWSGI ini file to enable default dynamic uwsgi process number
COPY deploy/docker/uwsgi.ini /etc/uwsgi/
# Copy supervisor config
#COPY deploy/docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

WORKDIR /code
ADD . /code/
RUN make deps

EXPOSE 3031

CMD ["/usr/local/bin/uwsgi", "--ini", "/etc/uwsgi/uwsgi.ini", "--py-autoreload", "1"]
