"""added rounds answers

Revision ID: 4667f38426eb
Revises: 380522bcdac1
Create Date: 2014-12-18 14:56:56.064146

"""

# revision identifiers, used by Alembic.
revision = '4667f38426eb'
down_revision = '380522bcdac1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

def upgrade():

	op.add_column('PostsForAnswers', sa.Column('round', sa.Integer(), nullable=False))
	populate = text(
		"UPDATE PostsForAnswers a " +
		"JOIN " +
		"(SELECT a.id, sum(jcount) as count " +
		"FROM PostsForAnswers a, " +
		"(SELECT ap.id, ap.postsforanswers_id1, ap.postsforanswers_id2, count(*) as jcount " +
		"FROM AnswerPairings ap " +
		"JOIN Judgements j " +
		"ON j.answerpairings_id = ap.id " +
		"GROUP BY ap.id) as ap " +
		"WHERE a.id = ap.postsforanswers_id1 OR a.id = ap.postsforanswers_id2 " +
		"GROUP BY a.id) custom " +
		"ON a.id = custom.id " +
		"SET a.round = custom.count;"
	)
	op.get_bind().execute(populate)

def downgrade():
	### commands auto generated by Alembic - please adjust! ###
	op.drop_column('PostsForAnswers', 'round')
	### end Alembic commands ###
