"""added student number

Revision ID: c9ad3551e18
Revises: 3ddca7ab950a
Create Date: 2014-10-09 09:20:43.891993

"""

# revision identifiers, used by Alembic.
revision = 'c9ad3551e18'
down_revision = '3ddca7ab950a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('student_no', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'Users', ['student_no'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users')
    op.drop_column('Users', 'student_no')
    ### end Alembic commands ###
